# SPDX-License-Identifier: GPL-3.0-or-later
#
# Organizr runtime image: nginx + PHP-FPM + cron under s6-overlay.
#
# Replaces ghcr.io/organizr/organizr:latest, which upstream has not rebuilt
# since 2023-12 (Alpine 3.18, EOL). The files under root/ come from
# https://github.com/organizr/docker-base and
# https://github.com/organizr/docker-organizr (GPL-3.0), adapted to PHP 8.3
# and s6-overlay 3. Like upstream, the container clones or updates Organizr
# from GitHub (branch v2-master) into /config/www/organizr on every start.
#
# Any change in this directory produces a new image tag, see build-images.sh.

FROM docker.io/library/alpine:3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

ENV TZ=Etc/UTC \
    HOME=/root \
    S6_BEHAVIOUR_IF_STAGE2_FAILS=2 \
    S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0 \
    S6_VERBOSITY=1 \
    fpm=false \
    branch=v2-master

RUN set -eux; \
    apk upgrade --no-cache; \
    apk add --no-cache \
        bash \
        ca-certificates \
        coreutils \
        git \
        logrotate \
        nginx \
        s6-overlay \
        shadow \
        tzdata \
        php83 \
        php83-curl \
        php83-fileinfo \
        php83-fpm \
        php83-ftp \
        php83-ldap \
        php83-mbstring \
        php83-mysqli \
        php83-openssl \
        php83-pdo \
        php83-pdo_sqlite \
        php83-session \
        php83-simplexml \
        php83-sqlite3 \
        php83-tokenizer \
        php83-xml \
        php83-xmlwriter \
        php83-zip; \
    # The legacy cont-init.d/services.d scripts call these by their v2 paths
    for tool in with-contenv s6-setuidgid s6-svc; do \
        [ -e "/usr/bin/${tool}" ] || ln -s "/command/${tool}" "/usr/bin/${tool}"; \
    done; \
    [ -e /usr/bin/php ] || ln -s php83 /usr/bin/php; \
    groupmod -g 1000 users; \
    useradd -u 911 -U -d /config -s /bin/false abc; \
    usermod -G users abc; \
    mkdir -p /config /defaults; \
    echo 'fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;' >> /etc/nginx/fastcgi_params; \
    rm -f /etc/nginx/conf.d/default.conf /etc/nginx/http.d/default.conf; \
    sed -i "s#/var/log/messages {}.*# #g" /etc/logrotate.conf; \
    sed -i 's#/usr/sbin/logrotate /etc/logrotate.conf#/usr/sbin/logrotate /etc/logrotate.conf -s /config/log/logrotate.status#g' /etc/periodic/daily/logrotate; \
    www=/etc/php83/php-fpm.d/www.conf; \
    sed -i "s#^listen = 127.0.0.1:9000#listen = /var/run/php8-fpm.sock#" "$www"; \
    sed -i "s#^;listen.owner = nobody#listen.owner = abc#" "$www"; \
    sed -i "s#^;listen.group = nobody#listen.group = abc#" "$www"; \
    sed -i "s#^;listen.mode = 0660#listen.mode = 0660#" "$www"; \
    sed -i "s#^pm = dynamic#pm = ondemand#" "$www"; \
    sed -i "s#^pm.max_children = 5#pm.max_children = 4000#" "$www"; \
    sed -i "s#^pm.start_servers = 2#;pm.start_servers = 2#" "$www"; \
    sed -i "s#^;pm.process_idle_timeout = 10s;#pm.process_idle_timeout = 10s;#" "$www"; \
    sed -i "s#^;pm.max_requests = 500#pm.max_requests = 0#" "$www"; \
    sed -i "s#^zlib.output_compression = Off#zlib.output_compression = On#" /etc/php83/php.ini; \
    grep -qx 'listen = /var/run/php8-fpm.sock' "$www"; \
    grep -qx 'listen.owner = abc' "$www"; \
    grep -qx 'pm = ondemand' "$www"; \
    rm -rf /var/cache/apk/* /tmp/*

COPY root/ /

EXPOSE 80
VOLUME /config

ENTRYPOINT ["/init"]
