#!/usr/bin/env python3

# SPDX-License-Identifier: GPL-3.0-or-later

import os

import agent
import agent.tasks

setup_mode = agent.read_envfile("organizr-setup.env")["ORGANIZR_SETUP_MODE"]

response = agent.tasks.run(
    agent_id=os.environ["AGENT_ID"],
    action="configure-module",
    data={
        "host": os.environ["TRAEFIK_HOST"],
        "http2https": os.environ["TRAEFIK_HTTP2HTTPS"] == "True",
        "lets_encrypt": os.environ["TRAEFIK_LETS_ENCRYPT"] == "True",
        "setup_mode": setup_mode,
    },
)
agent.assert_exp(response["exit_code"] == 0, "The configure-module subtask failed")
