#!/usr/bin/env python3

# SPDX-License-Identifier: GPL-3.0-or-later

import json
import os
import sys

json.dump(
    {
        "host": os.getenv("TRAEFIK_HOST", ""),
        "http2https": os.getenv("TRAEFIK_HTTP2HTTPS") == "True",
        "lets_encrypt": os.getenv("TRAEFIK_LETS_ENCRYPT") == "True",
    },
    fp=sys.stdout,
)
