#!/usr/bin/env python3

# SPDX-License-Identifier: GPL-3.0-or-later

import json
import sys

import agent

request = json.load(sys.stdin)
original_environment = request["environment"]

for variable in (
    "TRAEFIK_HOST",
    "TRAEFIK_HTTP2HTTPS",
    "TRAEFIK_LETS_ENCRYPT",
):
    if variable in original_environment:
        agent.set_env(variable, original_environment[variable])

agent.dump_env()
